const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { exec } = require('child_process');
const gm = require('gm');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const Jimp = require('jimp');

const app = express();
const PORT = process.env.PORT || 8000;

// Enable CORS
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  next();
});

// Configure S3 Client (Template configuration for AWS S3 uploads)
const s3Client = new S3Client({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || 'MOCK_AWS_ACCESS_KEY_ID',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || 'MOCK_AWS_SECRET_ACCESS_KEY'
  }
});

// Setup multer for satellite image uploads
const uploadDir = path.join(__dirname, 'uploads');
const outputDir = path.join(__dirname, 'outputs');

if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir);
if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadDir),
  filename: (req, file, cb) => cb(null, Date.now() + '-' + file.originalname)
});
const upload = multer({ storage });

// Serve outputs statically
app.use('/outputs', express.static(outputDir));

/**
 * Uploads processed satellite image to AWS S3 Bucket
 */
async function uploadToS3(filePath, bucketName, fileKey) {
  try {
    const fileStream = fs.createReadStream(filePath);
    const command = new PutObjectCommand({
      Bucket: bucketName,
      Key: fileKey,
      Body: fileStream,
      ContentType: 'image/png'
    });
    
    // In a real AWS environment with valid keys, this will upload to your bucket
    if (process.env.AWS_ACCESS_KEY_ID && process.env.AWS_ACCESS_KEY_ID !== 'MOCK_AWS_ACCESS_KEY_ID') {
      await s3Client.send(command);
      console.log(`[AWS S3] Uploaded successfully: s3://${bucketName}/${fileKey}`);
      return `https://${bucketName}.s3.amazonaws.com/${fileKey}`;
    } else {
      console.log(`[AWS S3 Mock] Successfully simulated upload of ${fileKey} to ${bucketName}`);
      return `/outputs/${path.basename(filePath)}`;
    }
  } catch (error) {
    console.error('[AWS S3 Error] Failed S3 Upload:', error.message);
    return null;
  }
}

/**
 * Image processing pipeline:
 * Tries GraphicsMagick/ImageMagick first, and falls back to pure Canvas-based processing
 * if the GM/IM command-line tools are not installed on the system path.
 */
/**
 * Image processing pipeline:
 * Spawns the python U-Net inference engine on the uploaded file.
 */
function processImage(inputPath, outputPath, callback) {
  console.log(`[Processing] Starting deep learning reconstruction on: ${path.basename(inputPath)}`);

  const pythonPath = 'python';
  const scriptPath = path.join(__dirname, '..', 'cloud-reconstruction', 'inference.py');
  const outputDir = path.join(__dirname, 'outputs');

  // Command to invoke python U-Net inference on the upload file
  const command = `"${pythonPath}" "${scriptPath}" --input "${inputPath}" --output "${outputDir}"`;
  console.log(`[Command] Executing: ${command}`);

  exec(command, (err, stdout, stderr) => {
    if (err) {
      console.error('[Inference Error] U-Net model failed to run:', err);
      console.error(stderr);
      return callback(err);
    }

    console.log('[Inference Success] Cloud removal finished.');
    console.log(stdout);

    // Locating outputs generated by inference.py under scene-specific folder
    const fileStem = path.basename(inputPath, path.extname(inputPath));
    const sceneOutputDir = path.join(outputDir, fileStem);

    const generatedRgb = path.join(sceneOutputDir, 'cloud_free_rgb.jpg');
    const generatedMetrics = path.join(sceneOutputDir, 'metrics.json');

    try {
      if (fs.existsSync(generatedRgb)) {
        // Copy processed output back to standard expected outputPath
        fs.copyFileSync(generatedRgb, outputPath);

        let ssim = 'Ground Truth Not Available';
        let fidelity = 'Ground Truth Not Available';
        let cloudFraction = '0.0%';

        if (fs.existsSync(generatedMetrics)) {
          const raw = JSON.parse(fs.readFileSync(generatedMetrics, 'utf8'));
          if (raw.cloud_fraction !== undefined) {
            cloudFraction = (raw.cloud_fraction * 100).toFixed(1) + '%';
          }
        }

        callback(null, {
          engine: 'U-Net Deep Learning Model (RTX 4050 GPU)',
          metrics: {
            structuralSimilarityIndex: ssim,
            spectralFidelityRatio: fidelity,
            cloudFraction: cloudFraction
          }
        });
      } else {
        callback(new Error('Reconstruction output files not found.'));
      }
    } catch (e) {
      callback(e);
    }
  });
}

// ---- API REST ENDPOINTS ----

/**
 * POST /api/process-satellite-image
 * Receives satellite file upload, runs preprocessing & AI pixel restoration
 */
app.post('/api/process-satellite-image', upload.single('image'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No image file uploaded' });
  }

  const inputPath = req.file.path;
  const outputFileName = 'reconstructed-' + req.file.filename + '.png';
  const outputPath = path.join(outputDir, outputFileName);

  // Process the satellite image
  processImage(inputPath, outputPath, async (err, result) => {
    if (err) {
      return res.status(500).json({ error: 'Failed to process satellite image', details: err.message });
    }

    // Attempt to upload processed image to S3 (bucket configuration)
    const bucketName = process.env.AWS_S3_BUCKET || 'clearsat-imagery-bucket';
    const fileKey = `processed/${outputFileName}`;
    const s3Url = await uploadToS3(outputPath, bucketName, fileKey);

    // Respond with metadata and output URLs
    res.json({
      success: true,
      message: 'LISS-IV Satellite imagery successfully preprocessed and reconstructed',
      engine: result.engine,
      originalName: req.file.originalname,
      tempUploadPath: inputPath,
      reconstructedImageLocalUrl: `/outputs/${outputFileName}`,
      reconstructedImageS3Url: s3Url || 'Upload simulated',
      resolution: '5.8 meters',
      sensorBandsProcessed: ['Green (B2)', 'Red (B3)', 'NIR (B4)', 'SWIR (B5/B6)'],
      metrics: result.metrics
    });
  });
});

// Start the server
app.listen(PORT, () => {
  console.log(`===============================================`);
  console.log(` ClearSat Image Processing Server started!     `);
  console.log(` Active Port: http://localhost:${PORT}          `);
  console.log(` Endpoint: POST /api/process-satellite-image   `);
  console.log(`===============================================`);
});
