const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { exec } = require('child_process');
const gm = require('gm');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const Jimp = require('jimp');

const app = express();
const PORT = process.env.PORT || 8000;

// Enable CORS
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  next();
});

// Middleware for parsing JSON and form data
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Configure S3 Client (Template configuration for AWS S3 uploads)
const s3Client = new S3Client({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || 'MOCK_AWS_ACCESS_KEY_ID',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || 'MOCK_AWS_SECRET_ACCESS_KEY'
  }
});

// Setup multer for satellite image uploads
const uploadDir = path.join(__dirname, 'uploads');
const outputDir = path.join(__dirname, 'outputs');

if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir);
if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadDir),
  filename: (req, file, cb) => cb(null, Date.now() + '-' + file.originalname)
});
const upload = multer({ storage });

// Serve outputs statically
app.use('/outputs', express.static(outputDir));
app.use('/uploads', express.static(uploadDir));

// Serve frontend static files
app.use(express.static(path.join(__dirname, '..', 'frontend')));

// Serve index.html for dashboard route
app.get('/dashboard', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'frontend', 'index.html'));
});

/**
 * Uploads processed satellite image to AWS S3 Bucket
 */
async function uploadToS3(filePath, bucketName, fileKey) {
  try {
    const fileStream = fs.createReadStream(filePath);
    const command = new PutObjectCommand({
      Bucket: bucketName,
      Key: fileKey,
      Body: fileStream,
      ContentType: 'image/png'
    });
    
    // In a real AWS environment with valid keys, this will upload to your bucket
    if (process.env.AWS_ACCESS_KEY_ID && process.env.AWS_ACCESS_KEY_ID !== 'MOCK_AWS_ACCESS_KEY_ID') {
      await s3Client.send(command);
      console.log(`[AWS S3] Uploaded successfully: s3://${bucketName}/${fileKey}`);
      return `https://${bucketName}.s3.amazonaws.com/${fileKey}`;
    } else {
      console.log(`[AWS S3 Mock] Successfully simulated upload of ${fileKey} to ${bucketName}`);
      return `/outputs/${path.basename(filePath)}`;
    }
  } catch (error) {
    console.error('[AWS S3 Error] Failed S3 Upload:', error.message);
    return null;
  }
}

/**
 * Image processing pipeline:
 * Tries GraphicsMagick/ImageMagick first, and falls back to pure Canvas-based processing
 * if the GM/IM command-line tools are not installed on the system path.
 */
/**
 * Image processing pipeline:
 * Spawns the python U-Net inference engine on the uploaded file.
 */
function processImage(inputPath, outputPath, callback) {
  console.log(`[Processing] Starting deep learning reconstruction on: ${path.basename(inputPath)}`);

  const pythonPath = 'python';
  const scriptPath = path.join(__dirname, '..', 'cloud-reconstruction', 'inference.py');
  const outputDir = path.join(__dirname, 'outputs');

  // Command to invoke python U-Net inference on the upload file
  const command = `"${pythonPath}" "${scriptPath}" --input "${inputPath}" --output "${outputDir}"`;
  console.log(`[Command] Executing: ${command}`);

  exec(command, (err, stdout, stderr) => {
    if (err) {
      console.error('[Inference Error] U-Net model failed to run:', err);
      console.error(stderr);
      return callback(err);
    }

    console.log('[Inference Success] Cloud removal finished.');
    console.log(stdout);

    // Locating outputs generated by inference.py under scene-specific folder
    const fileStem = path.basename(inputPath, path.extname(inputPath));
    const sceneOutputDir = path.join(outputDir, fileStem);

    const generatedRgb = path.join(sceneOutputDir, 'cloud_free_rgb.jpg');
    const generatedMetrics = path.join(sceneOutputDir, 'metrics.json');

    try {
      if (fs.existsSync(generatedRgb)) {
        // Copy processed output back to standard expected outputPath
        fs.copyFileSync(generatedRgb, outputPath);

        let ssim = 'Ground Truth Not Available';
        let fidelity = 'Ground Truth Not Available';
        let cloudFraction = '0.0%';

        if (fs.existsSync(generatedMetrics)) {
          const raw = JSON.parse(fs.readFileSync(generatedMetrics, 'utf8'));
          if (raw.cloud_fraction !== undefined) {
            cloudFraction = (raw.cloud_fraction * 100).toFixed(1) + '%';
          }
        }

        callback(null, {
          engine: 'Swin U-Net Deep Learning Model (RTX 4050 GPU)',
          metrics: {
            structuralSimilarityIndex: ssim,
            spectralFidelityRatio: fidelity,
            cloudFraction: cloudFraction
          }
        });
      } else {
        callback(new Error('Reconstruction output files not found.'));
      }
    } catch (e) {
      callback(e);
    }
  });
}

// ---- API REST ENDPOINTS ----

/**
 * POST /api/process-satellite-image
 * Receives satellite file upload, runs preprocessing & AI pixel restoration
 */
app.post('/api/process-satellite-image', upload.single('image'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No image file uploaded' });
  }

  const inputPath = req.file.path;
  const outputFileName = 'reconstructed-' + req.file.filename + '.png';
  const outputPath = path.join(outputDir, outputFileName);

  // Process the satellite image
  processImage(inputPath, outputPath, async (err, result) => {
    if (err) {
      return res.status(500).json({ error: 'Failed to process satellite image', details: err.message });
    }

    // Attempt to upload processed image to S3 (bucket configuration)
    const bucketName = process.env.AWS_S3_BUCKET || 'clearsat-imagery-bucket';
    const fileKey = `processed/${outputFileName}`;
    const s3Url = await uploadToS3(outputPath, bucketName, fileKey);

    // Respond with metadata and output URLs
    res.json({
      success: true,
      message: 'LISS-IV Satellite imagery successfully preprocessed and reconstructed',
      engine: result.engine,
      originalName: req.file.originalname,
      tempUploadPath: inputPath,
      reconstructedImageLocalUrl: `/outputs/${outputFileName}`,
      reconstructedImageS3Url: s3Url || 'Upload simulated',
      resolution: '5.8 meters',
      sensorBandsProcessed: ['Green (B2)', 'Red (B3)', 'NIR (B4)', 'SWIR (B5/B6)'],
      metrics: result.metrics
    });
  });
});

/**
 * POST /api/upload
 * Frontend-compatible upload endpoint - stores file and returns upload_id
 */
app.post('/api/upload', upload.single('file'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ detail: 'No file uploaded' });
  }

  try {
    const uploadId = Date.now().toString();
    const satelliteName = path.basename(req.file.originalname, path.extname(req.file.originalname));
    
    // Store upload metadata for later reference
    res.json({
      upload_id: uploadId,
      satellite_name: satelliteName,
      filename: req.file.filename,
      filepath: req.file.path,
      size: req.file.size
    });
  } catch (err) {
    res.status(500).json({ detail: 'Upload processing failed: ' + err.message });
  }
});

/**
 * POST /api/reconstruct
 * Frontend-compatible reconstruction endpoint - processes uploaded image
 */
app.post('/api/reconstruct', upload.any(), (req, res) => {
  const uploadId = req.body.upload_id;
  const patchSize = parseInt(req.body.patch_size) || 256;
  const stride = parseInt(req.body.stride) || 128;

  if (!uploadId) {
    return res.status(400).json({ detail: 'Missing upload_id' });
  }

  // Find the uploaded file from recent uploads
  try {
    const recentFiles = fs.readdirSync(uploadDir)
      .map(f => path.join(uploadDir, f))
      .filter(f => {
        try {
          return fs.statSync(f).mtime.getTime() > Date.now() - 600000; // Within 10 minutes
        } catch {
          return false;
        }
      })
      .sort((a, b) => {
        try {
          return fs.statSync(b).mtime - fs.statSync(a).mtime;
        } catch {
          return 0;
        }
      });

    if (recentFiles.length === 0) {
      return res.status(404).json({ detail: 'Uploaded file not found' });
    }

    const inputPath = recentFiles[0];
    const outputFileName = `reconstructed-${Date.now()}.png`;
    const outputPath = path.join(outputDir, outputFileName);

    // Process the image using the deep learning model
    processImage(inputPath, outputPath, async (err, result) => {
      if (err) {
        console.error('[Reconstruct Error]', err);
        return res.status(500).json({ detail: 'Reconstruction failed: ' + err.message });
      }

      try {
        const bucketName = process.env.AWS_S3_BUCKET || 'clearsat-imagery-bucket';
        const fileKey = `processed/${outputFileName}`;
        const s3Url = await uploadToS3(outputPath, bucketName, fileKey);
        const fileStem = path.basename(inputPath, path.extname(inputPath));
        
        let cloud_fraction = 0.0;
        let processing_time = null;
        try {
          const summaryPath = path.join(outputDir, 'inference_summary.json');
          if (fs.existsSync(summaryPath)) {
            const summaryData = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
            if (summaryData.length > 0) {
              cloud_fraction = summaryData[0].cloud_fraction || 0.0;
              processing_time = summaryData[0].time || null;
            }
          }
        } catch (e) {}

        res.json({
          success: true,
          upload_id: uploadId,
          cloud_fraction: cloud_fraction,
          inference_time: processing_time,
          processing_time: processing_time,
          reconstructed_image_url: `/outputs/${outputFileName}`,
          paths: {
            original: `/uploads/${path.basename(inputPath)}`,
            reconstructed: `/outputs/${outputFileName}`,
            mask: `/outputs/${fileStem}/cloud_mask.png`
          },
          s3_url: s3Url || 'Upload simulated',
          metrics: result.metrics,
          engine: result.engine,
          patch_size: patchSize,
          stride: stride
        });
      } catch (err) {
        console.error('[Response Error]', err);
        res.status(500).json({ detail: 'Response generation failed: ' + err.message });
      }
    });
  } catch (err) {
    console.error('[Reconstruct Exception]', err);
    res.status(500).json({ detail: 'Server error: ' + err.message });
  }
});

// Start the server
app.listen(PORT, () => {
  console.log(`===============================================`);
  console.log(` ClearSat Image Processing Server started!     `);
  console.log(` Active Port: http://localhost:${PORT}          `);
  console.log(` Endpoints:                                    `);
  console.log(`  • POST /api/upload                           `);
  console.log(`  • POST /api/reconstruct                      `);
  console.log(`  • POST /api/process-satellite-image          `);
  console.log(`===============================================`);
});
